### ISSUE TITLE
v3.1.1 version is raising Module parse failed: Unexpected token in index.mjs

### ISSUE THREAD

**Issue by mdissel** [jperasmus/stale-while-revalidate-cache#29]
I've added this component via npm and when i compile my code I get this exception when using v3.1.1 of this component. It does work correctly with version 2.2.0

ERROR in ./node_modules/stale-while-revalidate-cache/dist/index.mjs 516:41
Module parse failed: Unexpected token (516:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See [Concepts | webpack](https://webpack.js.org/concepts#loaders)

Node v16
Typescript 4.5

**Comment by jperasmus** [comment]
Hi, thanks for reporting the issue. I can see the error is thrown because of the Nullish coalescing operator (??) characters in the dist file. According to [Node.green](https://node.green/#ES2020-features--nullish-coalescing-operator-----), it has been supported since at least Node.js v14.5.0

Can you double-check the Node.js version that you're using when the build is running?

**Comment by mdissel** [comment]
I'm using Node v16.14.0

**Comment by jperasmus** [comment]
Thanks for the link. I'll take a look at releasing a version without nullish coalescing.

**Comment by jperasmus** [comment]
Hey Marco, v3.1.2 should now not contain any nullish coalescing operators.

**Comment by mdissel** [comment]
Thanks!
